# Default initial positions for robotic_arm's ros2_control fake system

initial_positions:
  taco_to_base_link: 0.0
  shoulder_link_to_taco: 0.0
  elbow_link_to_shoulder_link: 0.0
  bevel_housing_to_elbow_link: 0.0
  wrist_link_to_bevel_housing: 0.0
  moving_claw_to_end_effector_base: 0.0