# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  taco_to_base_link:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_link_to_taco:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: false
    max_acceleration: 0
  elbow_link_to_shoulder_link:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: false
    max_acceleration: 0
  bevel_housing_to_elbow_link:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_link_to_bevel_housing:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: false
    max_acceleration: 0
  moving_claw_to_end_effector_base:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: false
    max_acceleration: 0