# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    grip_action_controller:
      type: position_controllers/GripperActionController


    # joint_state_broadcaster:
    #   type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - taco_to_base_link
      - shoulder_link_to_taco
      - elbow_link_to_shoulder_link
      - bevel_housing_to_elbow_link
      - wrist_link_to_bevel_housing
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
grip_action_controller:
  ros__parameters:
    joint: moving_claw_to_end_effector_base