controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController
    
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

forward_position_controller:
  ros__parameters:
    joints:
      - shoulder_link_to_taco
      - elbow_link_to_shoulder_link
      - bevel_housing_to_elbow_link
      - wrist_link_to_bevel_housing
    interface_name: position
  
arm_controller:
  ros__parameters:
    joints:
      - shoulder_link_to_taco
      - elbow_link_to_shoulder_link
      - bevel_housing_to_elbow_link
      - wrist_link_to_bevel_housing   
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    stop_trajectory_duration: 0.2
    state_publish_rate:  100.0
    action_monitor_rate: 25.0
    goal_time: 0.0