options:
  dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 5
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  baudrate: 1000  # in kbps
  sync_period: 10000  # in microseconds
  heartbeat_consumer: true

defaults:
  dcf: "ZeroErr_Driver_V1_5.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  period: 10  # in milliseconds; should match master's SYNC period
  diagnostics:  # enable this if you want to see diagnostic msgs on the topic /diagnostics
    enable: true
    period: 1000
  switching_state: 2 # 2 is "Ready to switch on"; might need to change to 4 ("Operation Enabled")
  position_mode: 8
  scale_pos_to_dev: 83443.02680376362180  # Encoder counts to radians (2^19 / 2π)
  scale_pos_from_dev: 0.00001198422490  # Radians to encoder counts (2π / 2^19)
  sdo:
    - {index: 0x6081, sub_index: 0, value: 5566}  # Set Velocity
    - {index: 0x6083, sub_index: 0, value: 5566}  # Set Acceleration
    - {index: 0x6084, sub_index: 0, value: 5566}  # Set Deceleration
    # - {index: 0x6060, sub_index: 0, value: 8} # Set to Cyclic Synchronous Position mode
  tpdo:
    1:
      enabled: true
      cob_id: "auto" #Ox180
      transmission: 0x01
      mapping:
        - {index: 0x6041, sub_index: 0}  # status word 2 bytes
        - {index: 0x6061, sub_index: 0}  # mode of operation display 1 byte
    2:
      enabled: true
      cob_id: "auto" #0x280
      transmission: 0x01
      mapping:
        - {index: 0x6064, sub_index: 0}  # position actual value 4 bytes
        - {index: 0x606C, sub_index: 0}  # velocity actual value 4 bytes
    3:
      enabled: false
    4:
      enabled: false
  rpdo:
    1:
      enabled: true
      cob_id: "auto" #0x200
      mapping:
        - {index: 0x6040, sub_index: 0}  # controlword 2 bytes
        - {index: 0x6060, sub_index: 0}  # mode of operation 1 byte
    2:
      enabled: true
      cob_id: "auto" #0x300
      mapping:
        - {index: 0x607A, sub_index: 0}  # target position value 4 bytes

nodes:
  shoulder_link_to_taco:
    node_id: 1
  elbow_link_to_shoulder_link:
    node_id: 2
  bevel_housing_to_elbow_link:
    node_id: 3
  wrist_link_to_bevel_housing:
    node_id: 4
