options:
  dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 1
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  baudrate: 1000  # in kbps
  sync_period: 10000  # in microseconds
  heartbeat_consumer: true

defaults:
  dcf: "ZeroErr_Driver_V1.5.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  period: 10  # in milliseconds; should match master's SYNC period
  switching_state: 2  # 2 is "Ready to switch on"; might need to change to 4 ("Operation Enabled")
  position_mode: 7  # Interpolated Position Mode; set to 8 for Cyclic Synchronous Position Mode
  scale_pos_from_dev: 83443.02680376362180  # Encoder counts to radians (2^19 / 2π)
  scale_pos_to_dev: 0.00001198422490  # Radians to encoder counts (2π / 2^19)
  sdo:
    - {index: 0x6081, sub_index: 0, value: 5566}  # Set Velocity
    - {index: 0x6083, sub_index: 0, value: 5566}  # Set Acceleration
    - {index: 0x6084, sub_index: 0, value: 5566}  # Set Deceleration
    - {index: 0x60C2, sub_index: 1, value: 10}  # Set interpolation time for cyclic modes to 10 ms to match SYNC
    - {index: 0x60C2, sub_index: 2, value: -3}  # Set base 10^-3s (milliseconds)
  tpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6041, sub_index: 0}  # status word
        - {index: 0x6061, sub_index: 0}  # mode of operation display
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6064, sub_index: 0}  # position actual value
        - {index: 0x606C, sub_index: 0}  # velocity actual value
    3:
      enabled: false
    4:
      enabled: false
  rpdo:
    1:
      enabled: true
      cob_id: "auto"
      mapping:
        - {index: 0x6040, sub_index: 0}  # controlword
        - {index: 0x6060, sub_index: 0}  # mode of operation
        - {index: 0x60C1, sub_index: 1}  # interpolated position data
    2:
      enabled: true
      cob_id: "auto"
      mapping:
        - {index: 0x607A, sub_index: 0}  # target position

nodes:
  shoulder_motor:
    node_id: 2
  elbow_motor:
    node_id: 3
  wrist_right_motor:
    node_id: 4
  wrist_left_motor:
    node_id: 5
